import { DefaultProperties } from './Common.type';
import { Donor } from './Donor.type';
import { Platform } from './Platform.type';
import { Recipient } from './Recipient.type';

export type Give = {
  amount?: number | null;
  attachments?: string[] | null;
  detailEntry?: string | null;
  donor?: Donor;
  donorId?: string | null;
  donorLegacyId?: string | null;
  endDate?: Date | null;
  frequency?: string | null;
  fromEmail?: string | null;
  fromName?: string | null;
  giveCount?: number | null;
  giveCountTotal?: number | null;
  giveDate?: Date | null;
  headers?: string[] | object[] | null;
  htmlBody?: string | null;
  isFeatured?: boolean | null;
  isRecurring?: boolean | null;
  platform?: Platform;
  platformId?: string | null;
  platformLegacyId?: string | null;
  processDate?: Date | null;
  processUserId?: string | null;
  processUserLegacyId?: string | null;
  rawData?: string | null;
  recipient?: Recipient;
  recipientId?: string | null;
  recipientLegacyId?: string | null;
  splitAmount?: number | null;
  splitTaxDeductible?: number | null;
  splitType?: string | null;
  splitUnit?: string | null;
  startDate?: Date | null;
  status?: string | null;
  subject?: string | null;
  taxDeductible?: string | null;
  textBody?: string | null;
  timezone?: string | null;
  unit?: string | null;
} & DefaultProperties;
